### ISSUE TITLE
JS9 not actively developed anymore 

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/mmoda-frontend-drupal#10]
The developer is retiring and there are no plans to continue supporting JS9. We should consider if it is safe to continue using it.
See:
https://github.com/ericmandel/js9/issues/88

**Comment by volodymyrss** [comment]
That's unfortunate. I actually think it's time only coming now, with web-based data analysis in astronomy all over. AladinLite provides similar functionality, but not so much for X-ray. Yet then, X-ray is not in favor these days.

Security as in resilience to attacks is not strongly affected. We use here only JS part, which has relatively limited security implications. Each of us runs plenty of legacy JS while using browser, and the browser tries to combat misuse.

Security as in sustainability of supporting unsupported software - it's not a big deal for time being, it was not much supported anyway. In some 5 years it may become a problem.

So we can just do nothing special and hope someone takes over the JS9 project, maybe from some of the coming X-ray missions (if any).

Let's re-iterate on the meeting https://github.com/oda-hub/meetings/tree/main/2022-08-08

**Comment by volodymyrss** [comment]
will keep js9 for now, but also try https://github.com/oda-hub/mmoda-frontend-drupal/issues/11
