### ISSUE TITLE
swiftmailer library is not actually included in the repo

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/mmoda-frontend-drupal#7]
*frontend-drupal7-for-astrooda/sites/all/libraries/swiftmailer* seems to be included as a submodule, but its path is not in .gitmodules, so it is not accessible.
Container builds without it, then frontend breaks in some places (e.g. sign-in) with an error
```
Fatal error:  require_once(): Failed opening required '/var/www/astrooda/sites/all/libraries/swiftmailer/lib/swift_required.php' (include_path='.:/usr/local/lib/php') in /var/www/astrooda/sites/all/modules/swiftmailer/includes/classes/SWIFTMailSystem.inc on line 120
```

**Comment by dsavchenko** [comment]
https://github.com/oda-hub/frontend-chart/blob/b1557ed45d877ec25449e2f59e14674954563391/make.sh#L235

**Comment by dsavchenko** [comment]
> It was missing indeed and the reason was that the folder does contain a directory called ".git" After removing it, i succeed to push this library to github.

Wait, but it is now added while building the container https://github.com/oda-hub/frontend-container/blob/a3b13af9db25b1c5ef72fd05249419f69f3da1c0/Dockerfile#L92

**Comment by volodymyrss** [comment]
If swiftmailer is in `mmoda-frontend-drupal`, we do not need it anymore in the container.
Right now, there are too many swiftmailers:

```
./astrooda/sites/all/libraries/swiftmailer
./astrooda/sites/all/modules/swiftmailer
./astrooda/vendor/swiftmailer
./astrooda/vendor/swiftmailer/swiftmailer
```

Frontend is configured to use the container-added one https://github.com/oda-hub/frontend-chart/blob/master/make.sh#L236
We should probably use the one @motame  added, and set suitable config in https://github.com/oda-hub/mmoda-frontend-db.
What do you think?

**Comment by dsavchenko** [comment]
> We should probably use the one @motame added, and set suitable config in https://github.com/oda-hub/mmoda-frontend-db.

With this, there will be no need to run any additional build-time or start-time hooks. I think it's a good way.
